name: Autotest Workflow

on:
  workflow_dispatch:

jobs:
  autotest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start tests
        env:
          DATABASE_URL: "sqlite+aiosqlite:///:memory:"
          SECRET_KEY: "key"
          KAFKA_SERVERS: '["localhost:9092"]'
          S3_BASEURL: "http://localhost:9000"
          S3_REGION: "ru-central1"
          S3_ENDPOINT: "http://localhost:9000"
        run: python -m pytest -q